---
- name: Verify
  hosts: all
  become: true
  environment:
    http_proxy: "{{ lookup('env', 'http_proxy') | default(omit)  }}"
    https_proxy: "{{ lookup('env', 'https_proxy') | default(omit) }}"
    no_proxy: "{{ lookup('env', 'no_proxy') | default(omit) }}"
  tasks:
    - name: Include prepare variables
      ansible.builtin.include_vars: "../../vars/ubuntu-22.04.yaml"
    - name: include verification tasks
      ansible.builtin.include_tasks:
        file: "{{ item }}"
      loop:
        - verify_tasks/clean_packages.yml